consoleme_url: https://console.sudoconsultants.com
authentication_method: mtls # challenge or mtls
server:
  http_timeout: 20
  port: 9099
  metadata_port: 9090
  ecs_credential_provider_port: 9091
azure:
  tenant_id: "848d8c2f-dd1b-4584-9611-159a328ca523"
  client_id: "49b27df3-e1b1-4803-a96a-eaa12610d355"
vault:
  address: "https://44.192.61.55:8200"
  role: "pki/issue/sudorole"
  token: "root"
challenge_settings: # (Optional) Username can be provided. If it is not provided, user will be prompted on first authentication attempt
  user: zain@sudoconsultants.com
mtls_settings: # only needed if authentication_method is mtls
  old_cert_message: mTLS certificate is too old, please run [refresh command]
  ttl: "24h"
  common_name: "sudoconsultants.com"
  cert: mtls.crt
  key: mtls.key
  catrust: mtlsCA.pem
  insecure: false
  linux:
    - "/run/mtls/certificates"
    - "/mtls/certificates"
    - "$HOME/.mtls/certificates"
    - "$HOME/.mtls"
metadata:
  routes:
    - path: latest/user-data
    - path: latest/meta-data/local-ipv4
      data: "127.0.0.1"
    - path: latest/meta-data/local-hostname
      data: ip-127-0-0-1.us-west-2.compute.internal
